version: '3'
services:
  dispatcher:
    image: httpd:2.4
    ports:
      - 8181:80
    volumes:
      - ./httpd_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
  svjis-app:
    image: berk76/svjis-app:latest
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=svjis-db
      - DB_USERNAME=web
      - DB_PASSWORD=change-it
      - TZ=Europe/Prague
  svjis-db:
    image: jacobalberty/firebird:3.0.7
    ports:
      - 3050:3050
    environment:
      - ISC_PASSWORD=change-it
      - FIREBIRD_DATABASE=SVJIS_PRODUCTION
      - FIREBIRD_USER=web
      - FIREBIRD_PASSWORD=change-it
      - TZ=Europe/Prague
    volumes:
      - svjis-data:/firebird
  firebirdadmin:
    image: marianaldenhoevel/firebirdwebadmin:latest
    ports:
    - 8081:80
volumes:
  svjis-data:
    driver: local
