name: Docker compose test

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: |
        cd docker-compose
        docker-compose -f svjis-dev.yml up -d

    - name: Create schema
      run: |
        cd docker-compose
        docker cp ./create-schema.sh svjis_db:/firebird/
        docker exec -T -it svjis_db bash "/firebird/create-schema.sh"

    - name: Stop containers
      run: |
        cd docker-compose
        docker-compose -f svjis-dev.yml down
