name: Selenium test

on:
  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Selenium test
      run: |
        sudo apt install google-chrome-stable
        google-chrome --version
